[package]
name = "polars_hash"
version = "0.1.1"
edition = "2021"

[lib]
name = "polars_hash"
crate-type = ["cdylib"]

[dependencies]
polars = { version = "*" }
pyo3 = { version = "0.20", features = ["extension-module"] }
pyo3-polars = { version = "0.8", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
sha256 = { version = "1.4.0"}
# fasthash = { version = "0.4.0"}
wyhash = {version = "0.5.0"}

[target.'cfg(target_os = "linux")'.dependencies]
jemallocator = { version = "0.5", features = ["disable_initial_exec_tls"] }